use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // `equipo_costo_horario` es la extensión 1:1 de `insumo` para
        // `tipo = equipo_herramienta` cuando se trata de equipo propio
        // costado por depreciación/consumo (metodología SCT/CMIC), a
        // diferencia de `herramienta` (sin depreciación) y `equipo_rentado`
        // (de terceros) — ver diccionario de datos. Los campos `cf_*` de
        // cache se recalculan en
        // `EquipoCostoHorarioService::calcular_cargos_fijos`. La receta de
        // cargos variables vive en `equipo_costo_horario_detalle`; la
        // valuación por región en `equipo_costo_horario_costo` /
        // `equipo_costo_horario_costo_detalle`.
        manager
            .create_table(
                Table::create()
                    .table(EquipoCostoHorario::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(EquipoCostoHorario::InsumoId)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfCostoMaquina)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfValorLlantas)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfValorPiezasEspeciales)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfValorMaquina)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfValorRescatePorcentaje)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfValorRescate)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfVidaEconomicaAnios)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfHorasUsoAnual)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfVidaUtilHoras)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfTasaInteresAnualPorcentaje)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfTasaSegurosAnualPorcentaje)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfMantenimientoPorcentaje)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfDepreciacionHora)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfInversionHora)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfSeguroHora)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfMantenimientoHora)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorario::CfCargoFijoHora)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(EquipoCostoHorario::Table, EquipoCostoHorario::InsumoId)
                            .to(Insumo::Table, Insumo::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        // Receta plana no recursiva (consumo/operación), compartida entre
        // regiones. `cantidad` es de la receta; `costo`/`importe` cuelgan de
        // `equipo_costo_horario_costo_detalle`.
        manager
            .create_table(
                Table::create()
                    .table(EquipoCostoHorarioDetalle::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::Id)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::EquipoCostoHorarioInsumoId)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::DetalleInsumoId)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::Tipo)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioDetalle::Naturaleza).text())
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::Orden)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::Cantidad)
                            .decimal()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::Deleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::CreatedAt)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioDetalle::CreatedBy)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioDetalle::UpdatedAt).text())
                    .col(ColumnDef::new(EquipoCostoHorarioDetalle::UpdatedBy).text())
                    .col(ColumnDef::new(EquipoCostoHorarioDetalle::DeletedAt).text())
                    .col(ColumnDef::new(EquipoCostoHorarioDetalle::DeletedBy).text())
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioDetalle::Table,
                                EquipoCostoHorarioDetalle::EquipoCostoHorarioInsumoId,
                            )
                            .to(EquipoCostoHorario::Table, EquipoCostoHorario::InsumoId)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioDetalle::Table,
                                EquipoCostoHorarioDetalle::DetalleInsumoId,
                            )
                            .to(Insumo::Table, Insumo::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioDetalle::Table,
                                EquipoCostoHorarioDetalle::CreatedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioDetalle::Table,
                                EquipoCostoHorarioDetalle::UpdatedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioDetalle::Table,
                                EquipoCostoHorarioDetalle::DeletedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .to_owned(),
            )
            .await?;

        // Valuación regional: caches de variable + total. `region_id`
        // nullable = nacional; todo equipo nace con esa fila.
        manager
            .create_table(
                Table::create()
                    .table(EquipoCostoHorarioCosto::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::Id)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::EquipoCostoHorarioId)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioCosto::RegionId).text())
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::SubtotalConsumo)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::SubtotalOperacion)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::CargoVariableHora)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::CostoTotal)
                            .decimal()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioCosto::SincronizadoEn).text())
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::Deleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::CreatedAt)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCosto::CreatedBy)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioCosto::UpdatedAt).text())
                    .col(ColumnDef::new(EquipoCostoHorarioCosto::UpdatedBy).text())
                    .col(ColumnDef::new(EquipoCostoHorarioCosto::DeletedAt).text())
                    .col(ColumnDef::new(EquipoCostoHorarioCosto::DeletedBy).text())
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCosto::Table,
                                EquipoCostoHorarioCosto::EquipoCostoHorarioId,
                            )
                            .to(EquipoCostoHorario::Table, EquipoCostoHorario::InsumoId)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCosto::Table,
                                EquipoCostoHorarioCosto::RegionId,
                            )
                            .to(Region::Table, Region::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCosto::Table,
                                EquipoCostoHorarioCosto::CreatedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCosto::Table,
                                EquipoCostoHorarioCosto::UpdatedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCosto::Table,
                                EquipoCostoHorarioCosto::DeletedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(EquipoCostoHorarioCostoDetalle::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::Id)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::EquipoCostoHorarioCostoId)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::EquipoCostoHorarioDetalleId)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::Costo)
                            .decimal()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::Importe)
                            .decimal()
                            .not_null(),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioCostoDetalle::FechaPrecio).text())
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::Deleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::CreatedAt)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EquipoCostoHorarioCostoDetalle::CreatedBy)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(EquipoCostoHorarioCostoDetalle::UpdatedAt).text())
                    .col(ColumnDef::new(EquipoCostoHorarioCostoDetalle::UpdatedBy).text())
                    .col(ColumnDef::new(EquipoCostoHorarioCostoDetalle::DeletedAt).text())
                    .col(ColumnDef::new(EquipoCostoHorarioCostoDetalle::DeletedBy).text())
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCostoDetalle::Table,
                                EquipoCostoHorarioCostoDetalle::EquipoCostoHorarioCostoId,
                            )
                            .to(EquipoCostoHorarioCosto::Table, EquipoCostoHorarioCosto::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCostoDetalle::Table,
                                EquipoCostoHorarioCostoDetalle::EquipoCostoHorarioDetalleId,
                            )
                            .to(
                                EquipoCostoHorarioDetalle::Table,
                                EquipoCostoHorarioDetalle::Id,
                            )
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCostoDetalle::Table,
                                EquipoCostoHorarioCostoDetalle::CreatedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCostoDetalle::Table,
                                EquipoCostoHorarioCostoDetalle::UpdatedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                EquipoCostoHorarioCostoDetalle::Table,
                                EquipoCostoHorarioCostoDetalle::DeletedBy,
                            )
                            .to(Usuario::Table, Usuario::Id),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(EquipoCostoHorarioCostoDetalle::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(EquipoCostoHorarioCosto::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(EquipoCostoHorarioDetalle::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(EquipoCostoHorario::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum Insumo {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum Usuario {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum Region {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum EquipoCostoHorario {
    Table,
    InsumoId,
    CfCostoMaquina,
    CfValorLlantas,
    CfValorPiezasEspeciales,
    CfValorMaquina,
    CfValorRescatePorcentaje,
    CfValorRescate,
    CfVidaEconomicaAnios,
    CfHorasUsoAnual,
    CfVidaUtilHoras,
    CfTasaInteresAnualPorcentaje,
    CfTasaSegurosAnualPorcentaje,
    CfMantenimientoPorcentaje,
    CfDepreciacionHora,
    CfInversionHora,
    CfSeguroHora,
    CfMantenimientoHora,
    CfCargoFijoHora,
}

#[derive(DeriveIden)]
enum EquipoCostoHorarioDetalle {
    Table,
    Id,
    EquipoCostoHorarioInsumoId,
    DetalleInsumoId,
    Tipo,
    Naturaleza,
    Orden,
    Cantidad,
    Deleted,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
    DeletedAt,
    DeletedBy,
}

#[derive(DeriveIden)]
enum EquipoCostoHorarioCosto {
    Table,
    Id,
    EquipoCostoHorarioId,
    RegionId,
    SubtotalConsumo,
    SubtotalOperacion,
    CargoVariableHora,
    CostoTotal,
    SincronizadoEn,
    Deleted,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
    DeletedAt,
    DeletedBy,
}

#[derive(DeriveIden)]
enum EquipoCostoHorarioCostoDetalle {
    Table,
    Id,
    EquipoCostoHorarioCostoId,
    EquipoCostoHorarioDetalleId,
    Costo,
    Importe,
    FechaPrecio,
    Deleted,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
    DeletedAt,
    DeletedBy,
}
